version: '3.8'

services:
  lab-prueba-frontend:
    image: mcr.microsoft.com/devcontainers/typescript-node:22-bookworm
    volumes:
      - ..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    env_file:
      - ../.env

  lab-prueba-backend:
    image: mcr.microsoft.com/devcontainers/typescript-node:22-bookworm
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
    env_file:
      - ../.env

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../resources/database_backup.sql:/docker-entrypoint-initdb.d/database_backup.sql
    env_file:
      - ../.env
    ports:
      - "5432:5432"

volumes:
  postgres-data:
